language: node_js
node_js:
  - 0.12.4
sudo: false
after_success:
  - npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 4169......a046
    secure: S7v/CjEqe8qPVQ2/XJg+4ORCuA/pydpOPr9MNTPYPlMSSE26mNElngw/Vzg5AJXci9ISkQpiyOyhcsEGs5kWly+bIR/1mQZpnCy9qd8WvVtLf71N2pznK7US5gvI+3RwI3KKXwyz0Fl4mInciQY1opUze3DnJq4QsAOUezfshH64jZMM96Njbxp1Z0j8Bp7oGCSnCYIMUgo6vc+vZKVSMnPjLqkQxppbZlIUg2VmzWlabjUGUfr/5KYeVkJWgm9VeMFbxdW4V/UyhPKBlMFycsXbwzKdGR7bsVXV3eO//JS7tq9SrRmesYQunndgy7tJR7GqQyUdii99YUZKTV7CL+Tjj0kJJxTzLyEVqKMjtIkqHiCAjG6mQK97rZUdeWVej7WA/4Ee7FXblttGqh1u+mxd017p/JN4i+YBTpCgrHAmxpDcvwJ3MAFqfvI4MbSPMQmJnLmJmBzLMAKsW6RRnA793w/YmHUFlCws7FRhANy0uJpMH09gaQFhn9zXc2SuN8UF01/Eu5Dr5TjxO7bw0XvEa1GAL0w3mwVqUNgWKxd/dfeJMvGCqdox4+rnsqDjoftzAWKs7ASBc+FxDBdErSpArbb35bPnC4Of2+hsoQP3zoAEeneuRDLxMon3AyIV37nRq4OvtjqW6QsprBX3WHrXM8Tal/zMUAUSL5rCiGs=
  on:
    tags: true
    repo: Brightspace/frau-xsrf-token
